// ==UserScript==
// @name         MidenQuest - Dark Theme (Chris)
// @namespace    https://github.com/ChrisAB/MidenBlackTheme
// @version      0.1.2
// @description  MidenQuest Enhancement Script
// @author       Chris&Vibblez
// @require      https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js
// @include      http://www.midenquest.com/Game.aspx
// @include      http://midenquest.com/Game.aspx
// @grant        GM_xmlhttpRequest
// ==/UserScript==

(function() {
    'use strict';

    function addGlobalStyle(css) {
        var head, style;
        head = document.getElementsByTagName('head')[0];
        if (!head) { return; }

        style = document.createElement('style');
        style.type = 'text/css';
        style.innerHTML = css;
        head.appendChild(style);
    }
    $("#ChatLog").addClass('border2');

    addGlobalStyle('body {linear-gradient(rgb(63, 63, 63) 0px, rgb(0, 0, 0) 100%) rgb(63, 63, 63) !important; background-image: linear-gradient(rgb(63, 63, 63) 0px, rgb(0, 0, 0) 100%); background-position-x: initial; background-position-y: initial; background-size: initial; background-repeat-x: initial; background-repeat-y: initial; background-attachment: initial; background-origin: initial; background-clip: initial; background-color: rgb(63, 63, 63);}');
    addGlobalStyle('#ZoneContent { background: linear-gradient(rgb(12, 12, 12) 0px, rgb(27, 27, 27) 100%) rgb(12, 12, 12) !important; background-image: linear-gradient(rgb(12, 12, 12) 0px, rgb(27, 27, 27) 100%); background-position-x: initial; background-position-y: initial; background-size: initial; background-repeat-x: initial; background-repeat-y: initial; background-attachment: initial; background-origin: initial; background-clip: initial; background-color: rgb(12, 12, 12); }');
    addGlobalStyle('#ContentLoad { color: #FFFFFF!important ; }');
    addGlobalStyle('#TitleEmbedded { border-bottom: #000 2px solid;  }');
    addGlobalStyle('#ZoneOptions { background: linear-gradient(rgb(12, 12, 12) 0px, rgb(27, 27, 27) 100%) rgb(12, 12, 12) !important; background-image: linear-gradient(rgb(12, 12, 12) 0px, rgb(27, 27, 27) 100%); background-position-x: initial; background-position-y: initial; background-size: initial; background-repeat-x: initial; background-repeat-y: initial; background-attachment: initial; background-origin: initial; background-clip: initial; background-color: rgb(12, 12, 12); }');
    addGlobalStyle('#ZoneChat { background: linear-gradient(rgb(12, 12, 12) 0px, rgb(27, 27, 27) 100%) rgb(12, 12, 12) !important; background-image: linear-gradient(rgb(12, 12, 12) 0px, rgb(27, 27, 27) 100%); background-position-x: initial; background-position-y: initial; background-size: initial; background-repeat-x: initial; background-repeat-y: initial; background-attachment: initial; background-origin: initial; background-clip: initial; background-color: rgb(12, 12, 12); }');
    addGlobalStyle('#ChatLog { background: linear-gradient(rgb(12, 12, 12) 0px, rgb(27, 27, 27) 100%) rgb(12, 12, 12) !important; background-image: linear-gradient(rgb(12, 12, 12) 0px, rgb(27, 27, 27) 100%); background-position-x: initial; background-position-y: initial; background-size: initial; background-repeat-x: initial; background-repeat-y: initial; background-attachment: initial; background-origin: initial; background-clip: initial; background-color: rgb(12, 12, 12); }');
    addGlobalStyle('#ChatLog.border2 { box-shadow: rgb(1, 176, 170) 0px 0px 0px 1px; border-image-source: initial;border-image-slice: initial;border-image-width: initial;border-image-outset: initial;border-image-repeat: initial;border-width: 1px;border-style: solid;border-color: rgb(1, 176, 170);border-top-color: rgb(1, 176, 170);border-right-color: rgb(1, 176, 170);border-bottom-color: rgb(1, 176, 170);border-left-color: rgb(1, 176, 170);border-radius: 5px;}');
    addGlobalStyle('#chatShout1 { color: rgb(255,255,255)!important }');
    addGlobalStyle('#chatShout1 > span:nth-child(2) { color: rgb(255,255,255)!important }');
    addGlobalStyle('#InfoZone { border-bottom: 2px solid #000000 !important; }');
    addGlobalStyle('#MiniMap { border: 2px solid #000000 !important; }');
    addGlobalStyle('.ui-widget-content { border: 1px solid #111; background: #909090; color: #333333; }');
    addGlobalStyle('.prgactionwrapper > #prgactiontimer { border: 1px solid #111; background: #909090; color: #333333; }');
    addGlobalStyle('.prgactionwrapper > #prgactiontimer > .ui-widget-header { border: 1px solid #111; background: #646464; color: #333333; }');
    addGlobalStyle('.ui-widget-header { border: 1px solid #000000 !important; background: #555 !important; color: #ffffff; font-weight: bold; font-size: 1em !important; height: 20px !important; margin: 1px; padding-top: 2px; }');
    addGlobalStyle('.ui-widget-content { box-shadow: rgb(1, 176, 170) 0px 0px 0px 1px; border-image-source: initial;border-image-slice: initial;border-image-width: initial;border-image-outset: initial;border-image-repeat: initial;border-width: 1px;border-style: solid;border-color: rgb(1, 176, 170);border-top-color: rgb(1, 176, 170);border-right-color: rgb(1, 176, 170);border-bottom-color: rgb(1, 176, 170);border-left-color: rgb(1, 176, 170);border-radius: 5px; color: #FFF; background-image: linear-gradient(rgb(63, 63, 63) 0px, rgb(0, 0, 0) 100%); background-position-x: initial;background-position-y: initial; background-size: initial;background-repeat-x: initial;background-repeat-y: initial;background-attachment: initial;background-origin: initial;background-clip: initial;background-color: rgb(63, 63, 63);}');
    addGlobalStyle('#KingdomMap { border: 2px #000 solid !important; }');
    addGlobalStyle('#KingdomMap + div { border-left: 2px #000 solid !important; border-right: 2px #000 solid !important; border-bottom: 2px #000 solid !important; }');
    addGlobalStyle('.TradeskillSection { color: #999 !important; background-color: #333 !important; }');
    addGlobalStyle('.SearchLinkDiv { color: #01B0AA!important; box-shadow: rgb(1, 176, 170) 0px 0px 0px 1px; border-image-source: initial;border-image-slice: initial;border-image-width: initial;border-image-outset: initial;border-image-repeat: initial;border-width: 1px;border-style: solid;border-color: rgb(1, 176, 170);border-top-color: rgb(1, 176, 170);border-right-color: rgb(1, 176, 170);border-bottom-color: rgb(1, 176, 170);border-left-color: rgb(1, 176, 170);border-radius: 5px; margin: 3px; border: 2px solid; border-radius: 25px; background: linear-gradient(rgb(3, 128, 124) 0px, rgb(2, 82, 79) 100%) rgb(3, 128, 124)!important;background-image: linear-gradient(rgb(3, 128, 124) 0px, rgb(2, 82, 79) 100%)!important;background-position-x: initial ;background-position-y: initial;background-size: initial;background-repeat-x: initial;background-repeat-y: initial;background-attachment: initial;background-origin: initial;background-clip: initial;background-color:rgb(3, 128, 124)!important; cursor: pointer; height: 36px; }');
    addGlobalStyle('.SearchLinkDiv.border2 { box-shadow: rgb(1, 176, 170) 0px 0px 0px 1px; border-image-source: initial;border-image-slice: initial;border-image-width: initial;border-image-outset: initial;border-image-repeat: initial;border-width: 1px;border-style: solid;border-color: rgb(1, 176, 170);border-top-color: rgb(1, 176, 170);border-right-color: rgb(1, 176, 170);border-bottom-color: rgb(1, 176, 170);border-left-color: rgb(1, 176, 170);border-radius: 5px;}');
    addGlobalStyle('.SearchLinkSimpleName { color: #FF9900 }');
    addGlobalStyle('.drop_menu li:hover ul { background-color: #555 !important;}');
	addGlobalStyle('.drop_menu li:hover ul li a:hover { background: #777; }');
    addGlobalStyle('.SearchLinkDiv:hover { background: rgb(6, 173, 167)!important; }');
    addGlobalStyle('.gmButtonMed { box-shadow: rgb(1, 176, 170) 0px 0px 0px 1px; border-image-source: initial;border-image-slice: initial;border-image-width: initial;border-image-outset: initial;border-image-repeat: initial;border-width: 1px;border-style: solid;border-color: rgb(1, 176, 170);border-top-color: rgb(1, 176, 170);border-right-color: rgb(1, 176, 170);border-bottom-color: rgb(1, 176, 170);border-left-color: rgb(1, 176, 170);border-radius: 5px;background: linear-gradient(rgb(3, 128, 124) 0px, rgb(2, 82, 79) 100%) rgb(3, 128, 124)!important;background-image: linear-gradient(rgb(3, 128, 124) 0px, rgb(2, 82, 79) 100%)!important;background-position-x: initial ;background-position-y: initial;background-size: initial;background-repeat-x: initial;background-repeat-y: initial;background-attachment: initial;background-origin: initial;background-clip: initial;background-color:rgb(3, 128, 124)!important;}');
    addGlobalStyle('.gmButtonMed.border2 { box-shadow: rgb(1, 176, 170) 0px 0px 0px 1px; border-image-source: initial;border-image-slice: initial;border-image-width: initial;border-image-outset: initial;border-image-repeat: initial;border-width: 1px;border-style: solid;border-color: rgb(1, 176, 170);border-top-color: rgb(1, 176, 170);border-right-color: rgb(1, 176, 170);border-bottom-color: rgb(1, 176, 170);border-left-color: rgb(1, 176, 170);border-radius: 5px;}');
    addGlobalStyle('.gmButtonMed:hover { background: rgb(6, 173, 167)!important; }');
    addGlobalStyle('.gmButtonBig { box-shadow: rgb(1, 176, 170) 0px 0px 0px 1px; border-image-source: initial;border-image-slice: initial;border-image-width: initial;border-image-outset: initial;border-image-repeat: initial;border-width: 1px;border-style: solid;border-color: rgb(1, 176, 170);border-top-color: rgb(1, 176, 170);border-right-color: rgb(1, 176, 170);border-bottom-color: rgb(1, 176, 170);border-left-color: rgb(1, 176, 170);border-radius: 5px;background: linear-gradient(rgb(3, 128, 124) 0px, rgb(2, 82, 79) 100%) rgb(3, 128, 124)!important;background-image: linear-gradient(rgb(3, 128, 124) 0px, rgb(2, 82, 79) 100%)!important;background-position-x: initial ;background-position-y: initial;background-size: initial;background-repeat-x: initial;background-repeat-y: initial;background-attachment: initial;background-origin: initial;background-clip: initial;background-color:rgb(3, 128, 124)!important;}');
    addGlobalStyle('.gmButtonBig.border2 { box-shadow: rgb(1, 176, 170) 0px 0px 0px 1px; border-image-source: initial;border-image-slice: initial;border-image-width: initial;border-image-outset: initial;border-image-repeat: initial;border-width: 1px;border-style: solid;border-color: rgb(1, 176, 170);border-top-color: rgb(1, 176, 170);border-right-color: rgb(1, 176, 170);border-bottom-color: rgb(1, 176, 170);border-left-color: rgb(1, 176, 170);border-radius: 5px;}');
    addGlobalStyle('.gmButtonBig:hover { background: rgb(6, 173, 167)!important; }');
    addGlobalStyle('#BackSearch { box-shadow: rgb(1, 176, 170) 0px 0px 0px 1px; border-image-source: initial;border-image-slice: initial;border-image-width: initial;border-image-outset: initial;border-image-repeat: initial;border-width: 1px;border-style: solid;border-color: rgb(1, 176, 170);border-top-color: rgb(1, 176, 170);border-right-color: rgb(1, 176, 170);border-bottom-color: rgb(1, 176, 170);border-left-color: rgb(1, 176, 170);border-radius: 5px;color: #FF9900; background: linear-gradient(rgb(3, 128, 124) 0px, rgb(2, 82, 79) 100%) rgb(3, 128, 124)!important;background-image: linear-gradient(rgb(3, 128, 124) 0px, rgb(2, 82, 79) 100%)!important;background-position-x: initial ;background-position-y: initial;background-size: initial;background-repeat-x: initial;background-repeat-y: initial;background-attachment: initial;background-origin: initial;background-clip: initial;background-color:rgb(3, 128, 124)!important;}');
    addGlobalStyle('#BackSearch > span { box-shadow: rgb(1, 176, 170) 0px 0px 0px 1px; border-image-source: initial;border-image-slice: initial;border-image-width: initial;border-image-outset: initial;border-image-repeat: initial;border-width: 2px;border-color: rgb(1, 176, 170);border-top-color: rgb(1, 176, 170);border-right-color: rgb(1, 176, 170);border-bottom-color: rgb(1, 176, 170);border-left-color: rgb(1, 176, 170);border-radius: 5px; background: linear-gradient(rgb(3, 128, 124) 0px, rgb(2, 82, 79) 100%) rgb(3, 128, 124)!important;background-image: linear-gradient(rgb(3, 128, 124) 0px, rgb(2, 82, 79) 100%)!important;background-position-x: initial ;background-position-y: initial;background-size: initial;background-repeat-x: initial;background-repeat-y: initial;background-attachment: initial;background-origin: initial;background-clip: initial;background-color:rgb(3, 128, 124)!important;}');
    addGlobalStyle('#BackSearch:hover span { background: rgb(6, 173, 167)!important; }');
    addGlobalStyle('#BackSearch:hover { background: rgb(6, 173, 167)!important; }');
    addGlobalStyle('#BackMenu { box-shadow: rgb(1, 176, 170) 0px 0px 0px 1px; border-image-source: initial;border-image-slice: initial;border-image-width: initial;border-image-outset: initial;border-image-repeat: initial;border-width: 1px;border-style: solid;border-color: rgb(1, 176, 170);border-top-color: rgb(1, 176, 170);border-right-color: rgb(1, 176, 170);border-bottom-color: rgb(1, 176, 170);border-left-color: rgb(1, 176, 170);border-radius: 5px;color: #FF9900; background: linear-gradient(rgb(3, 128, 124) 0px, rgb(2, 82, 79) 100%) rgb(3, 128, 124)!important;background-image: linear-gradient(rgb(3, 128, 124) 0px, rgb(2, 82, 79) 100%)!important;background-position-x: initial ;background-position-y: initial;background-size: initial;background-repeat-x: initial;background-repeat-y: initial;background-attachment: initial;background-origin: initial;background-clip: initial;background-color:rgb(3, 128, 124)!important;}');
    addGlobalStyle('#BackMenu > span { box-shadow: rgb(1, 176, 170) 0px 0px 0px 1px; border-image-source: initial;border-image-slice: initial;border-image-width: initial;border-image-outset: initial;border-image-repeat: initial;border-width: 2px;border-color: rgb(1, 176, 170);border-top-color: rgb(1, 176, 170);border-right-color: rgb(1, 176, 170);border-bottom-color: rgb(1, 176, 170);border-left-color: rgb(1, 176, 170);border-radius: 5px; background: linear-gradient(rgb(3, 128, 124) 0px, rgb(2, 82, 79) 100%) rgb(3, 128, 124)!important;background-image: linear-gradient(rgb(3, 128, 124) 0px, rgb(2, 82, 79) 100%)!important;background-position-x: initial ;background-position-y: initial;background-size: initial;background-repeat-x: initial;background-repeat-y: initial;background-attachment: initial;background-origin: initial;background-clip: initial;background-color:rgb(3, 128, 124)!important;}');
    addGlobalStyle('#BackMenu:hover span { background: rgb(6, 173, 167)!important; }');
    addGlobalStyle('#BackMenu:hover { background: rgb(6, 173, 167)!important; }');
    addGlobalStyle('#BackTown { box-shadow: rgb(1, 176, 170) 0px 0px 0px 1px; border-image-source: initial;border-image-slice: initial;border-image-width: initial;border-image-outset: initial;border-image-repeat: initial;border-width: 1px;border-style: solid;border-color: rgb(1, 176, 170);border-top-color: rgb(1, 176, 170);border-right-color: rgb(1, 176, 170);border-bottom-color: rgb(1, 176, 170);border-left-color: rgb(1, 176, 170);border-radius: 5px;color: #FF9900; background: linear-gradient(rgb(3, 128, 124) 0px, rgb(2, 82, 79) 100%) rgb(3, 128, 124)!important;background-image: linear-gradient(rgb(3, 128, 124) 0px, rgb(2, 82, 79) 100%)!important;background-position-x: initial ;background-position-y: initial;background-size: initial;background-repeat-x: initial;background-repeat-y: initial;background-attachment: initial;background-origin: initial;background-clip: initial;background-color:rgb(3, 128, 124)!important;}');
    addGlobalStyle('#BackTown.border2 { box-shadow: rgb(1, 176, 170) 0px 0px 0px 1px; border-image-source: initial;border-image-slice: initial;border-image-width: initial;border-image-outset: initial;border-image-repeat: initial;border-width: 1px;border-style: solid;border-color: rgb(1, 176, 170);border-top-color: rgb(1, 176, 170);border-right-color: rgb(1, 176, 170);border-bottom-color: rgb(1, 176, 170);border-left-color: rgb(1, 176, 170);border-radius: 5px;}');
    addGlobalStyle('#BackTown > span { box-shadow: rgb(1, 176, 170) 0px 0px 0px 1px; border-image-source: initial;border-image-slice: initial;border-image-width: initial;border-image-outset: initial;border-image-repeat: initial;border-width: 2px;border-color: rgb(1, 176, 170);border-top-color: rgb(1, 176, 170);border-right-color: rgb(1, 176, 170);border-bottom-color: rgb(1, 176, 170);border-left-color: rgb(1, 176, 170);border-radius: 5px; background: linear-gradient(rgb(3, 128, 124) 0px, rgb(2, 82, 79) 100%) rgb(3, 128, 124)!important;background-image: linear-gradient(rgb(3, 128, 124) 0px, rgb(2, 82, 79) 100%)!important;background-position-x: initial ;background-position-y: initial;background-size: initial;background-repeat-x: initial;background-repeat-y: initial;background-attachment: initial;background-origin: initial;background-clip: initial;background-color:rgb(3, 128, 124)!important;}');
    addGlobalStyle('#BackTown:hover span { background: rgb(6, 173, 167)!important; }');
    addGlobalStyle('#BackTown:hover { background: rgb(6, 173, 167)!important; }');
    addGlobalStyle('#BackAccount { box-shadow: rgb(1, 176, 170) 0px 0px 0px 1px; border-image-source: initial;border-image-slice: initial;border-image-width: initial;border-image-outset: initial;border-image-repeat: initial;border-width: 1px;border-style: solid;border-color: rgb(1, 176, 170);border-top-color: rgb(1, 176, 170);border-right-color: rgb(1, 176, 170);border-bottom-color: rgb(1, 176, 170);border-left-color: rgb(1, 176, 170);border-radius: 5px;color: #FF9900; background: linear-gradient(rgb(3, 128, 124) 0px, rgb(2, 82, 79) 100%) rgb(3, 128, 124)!important;background-image: linear-gradient(rgb(3, 128, 124) 0px, rgb(2, 82, 79) 100%)!important;background-position-x: initial ;background-position-y: initial;background-size: initial;background-repeat-x: initial;background-repeat-y: initial;background-attachment: initial;background-origin: initial;background-clip: initial;background-color:rgb(3, 128, 124)!important;}');
    addGlobalStyle('#BackAccount > span { box-shadow: rgb(1, 176, 170) 0px 0px 0px 1px; border-image-source: initial;border-image-slice: initial;border-image-width: initial;border-image-outset: initial;border-image-repeat: initial;border-width: 2px;border-color: rgb(1, 176, 170);border-top-color: rgb(1, 176, 170);border-right-color: rgb(1, 176, 170);border-bottom-color: rgb(1, 176, 170);border-left-color: rgb(1, 176, 170);border-radius: 5px; background: linear-gradient(rgb(3, 128, 124) 0px, rgb(2, 82, 79) 100%) rgb(3, 128, 124)!important;background-image: linear-gradient(rgb(3, 128, 124) 0px, rgb(2, 82, 79) 100%)!important;background-position-x: initial ;background-position-y: initial;background-size: initial;background-repeat-x: initial;background-repeat-y: initial;background-attachment: initial;background-origin: initial;background-clip: initial;background-color:rgb(3, 128, 124)!important;}');
    addGlobalStyle('#BackAccount:hover span { background: rgb(6, 173, 167)!important; }');
    addGlobalStyle('#BackAccount:hover { background: rgb(6, 173, 167)!important; }');
    addGlobalStyle('.TabSel div { background: #333 !important;    color: #999 !important; }');
	addGlobalStyle('.Tabs li:hover div { background: #333 !important;    color: #999 !important; }');
	addGlobalStyle('.TabSel:hover div { background: #333 !important;    color: #999 !important;}');
	addGlobalStyle('.Tabs li { text-shadow: 1px 1px 0 #777 !important; }');
    addGlobalStyle('.CrumbBar>div>span { width: 21px; }');
    addGlobalStyle('.ui-button { padding: 0px!important; }');
    addGlobalStyle('.ui-button-text { box-shadow: rgb(1, 176, 170) 0px 0px 0px 1px; border-image-source: initial;border-image-slice: initial;border-image-width: initial;border-image-outset: initial;border-image-repeat: initial;border-width: 1px;border-style: solid;border-color: rgb(1, 176, 170);border-top-color: rgb(1, 176, 170);border-right-color: rgb(1, 176, 170);border-bottom-color: rgb(1, 176, 170);border-left-color: rgb(1, 176, 170);border-radius: 5px;color: #FF9900; background: linear-gradient(rgb(3, 128, 124) 0px, rgb(2, 82, 79) 100%) rgb(3, 128, 124)!important;background-image: linear-gradient(rgb(3, 128, 124) 0px, rgb(2, 82, 79) 100%)!important;background-position-x: initial ;background-position-y: initial;background-size: initial;background-repeat-x: initial;background-repeat-y: initial;background-attachment: initial;background-origin: initial;background-clip: initial;background-color:rgb(3, 128, 124)!important;}');
    addGlobalStyle('.ui-button-text:hover {  background: rgb(6, 173, 167)!important; }');
    addGlobalStyle('.ui-corner-all { -webkit-border-bottom-right-radius: 7px!important;-webkit-border-bottom-left-radius: 7px!important;-webkit-border-top-right-radius: 7px!important;-webkit-border-top-left-radius: 7px!important; }');
})();
